#!/bin/bash

#
# Finds commits that have edited specified line(s) for te file
#
# From: http://stackoverflow.com/questions/14142609/git-discover-which-commits-ever-touched-a-range-of-lines
#

git rev-list HEAD -- $1 | ( 
    while read rev; do
        git blame -l -L $2,+$3 $rev -- $1 | cut -d ' ' -f 1
    done;
) | awk '{ if (!h[$0]) { print $0; h[$0]=1 } }' | xargs -L 1 git log --oneline -1
